### ISSUE TITLE
Market Order Buy/Sell

### ISSUE THREAD

**Issue by Rutuparn9** [ChinmayPillai/Real_Estate_Broker_WebApp#2]
When a market-order buy/sell order is placed, a "Confirm Bid" pop-up shows with the message : "Are you sure you want to submit a bid of Rs X?"

Here X shows up as the LTP whereas the order is placed at top-sell bid(for buy order) and top-buy-bid(for sell order)

**Comment by Shivangp4** [comment]
Resolved. 
Now the popup message shows the message : "Are you sure you want to submit a bid of <current top bid>?"
