### ISSUE TITLE
Multiple Sell bids

### ISSUE THREAD

**Issue by Rutuparn9** [ChinmayPillai/Real_Estate_Broker_WebApp#6]
If a user places multiple sell bids, when the property is sold, only one of these bids clears and the rest of the bids placed by this user still persist.

**Comment by luthanhar** [comment]
This is related to marketOrder and limitOrder APIs created by Chinmay. Please handle the following edge case.

**Comment by ChinmayPillai** [comment]
Initial plans were to have multiple quantities of each property (apartment houses, subplots of a large land etc.) being traded and hence this wouldn't require clearing all other bids by the user. 

But we then pivoted the design to treat each of them as different properties to account for the varying demands and prices of different houses/subplots within the same apartment/land. 

In this design, it would indeed be a good feature to clear all other bids on the property by the user.

**Comment by ChinmayPillai** [comment]
Resolved in commit a4131600a90405aae55ae5ad21232047ff17f693
