### ISSUE TITLE
Unable to buy sold property

### ISSUE THREAD

**Issue by mridul-g** [ChinmayPillai/Real_Estate_Broker_WebApp#7]
After a user sells his property, 
1) If he places a Market Order Buy he is not able to buy it back, the message : "You can't buy your own property" is received.
2) But a Limit Order Buy is placed.

**Comment by luthanhar** [comment]
This is related to Issue #6, where even after transaction, all the previous bids are not cleared. Ideally placing a market buy order (if a sell bid exists) and limit order buy both should be allowed.
